package returns_test

import (
	"errors"
	"reflect"
	"testing"
	"time"

	returnDTO "backend/internal/app/dto/return"
	"backend/internal/app/entity"
	"backend/internal/app/enum"
	returnRepo "backend/internal/app/repository/return"
	returnService "backend/internal/app/service/return"

	"gorm.io/gorm"
)

// Callbacks are required: an unexpected read or write must fail the test.
type mockReturnRepo struct {
	t                 *testing.T
	called            map[string]int
	getStatusCountsFn func(string) ([]returnDTO.ReturnStatusCount, error)
	getListFn         func(string, string, int, int) ([]entity.SalesReturn, int64, error)
	searchOrdersFn    func(string) ([]entity.SaleOrder, error)
	getReturnFn       func(uint) (*entity.SalesReturn, error)
	createReturnFn    func(*entity.SalesReturn, []entity.SalesReturnItem) error
	approveReturnFn   func(uint, uint) error
	processRefundFn   func(uint, uint) error
	updateReturnFn    func(*entity.SalesReturn) error
	deleteReturnFn    func(uint) error
}

var _ returnRepo.ReturnRepository = (*mockReturnRepo)(nil)

func newMockReturnRepo(t *testing.T) *mockReturnRepo {
	t.Helper()
	return &mockReturnRepo{t: t, called: make(map[string]int)}
}

func (m *mockReturnRepo) expect(name string, configured bool) {
	m.t.Helper()
	m.called[name]++
	if !configured {
		m.t.Fatalf("unexpected repository call: %s", name)
	}
}

func (m *mockReturnRepo) GetStatusCounts(search string) ([]returnDTO.ReturnStatusCount, error) {
	m.expect("GetStatusCounts", m.getStatusCountsFn != nil)
	return m.getStatusCountsFn(search)
}

func (m *mockReturnRepo) GetList(search, status string, limit, offset int) ([]entity.SalesReturn, int64, error) {
	m.expect("GetList", m.getListFn != nil)
	return m.getListFn(search, status, limit, offset)
}

func (m *mockReturnRepo) SearchReturnableSaleOrders(keyword string) ([]entity.SaleOrder, error) {
	m.expect("SearchReturnableSaleOrders", m.searchOrdersFn != nil)
	return m.searchOrdersFn(keyword)
}

func (m *mockReturnRepo) GetReturnByID(id uint) (*entity.SalesReturn, error) {
	m.expect("GetReturnByID", m.getReturnFn != nil)
	return m.getReturnFn(id)
}

func (m *mockReturnRepo) CreateReturn(ret *entity.SalesReturn, items []entity.SalesReturnItem) error {
	m.expect("CreateReturn", m.createReturnFn != nil)
	return m.createReturnFn(ret, items)
}

func (m *mockReturnRepo) ApproveReturn(id, actor uint) error {
	m.expect("ApproveReturn", m.approveReturnFn != nil)
	return m.approveReturnFn(id, actor)
}

func (m *mockReturnRepo) ProcessRefund(id, actor uint) error {
	m.expect("ProcessRefund", m.processRefundFn != nil)
	return m.processRefundFn(id, actor)
}

func (m *mockReturnRepo) UpdateReturn(ret *entity.SalesReturn) error {
	m.expect("UpdateReturn", m.updateReturnFn != nil)
	return m.updateReturnFn(ret)
}

func (m *mockReturnRepo) DeleteReturn(id uint) error {
	m.expect("DeleteReturn", m.deleteReturnFn != nil)
	return m.deleteReturnFn(id)
}

func TestCreateReturn_ApprovalUsesAuthenticatedRole(t *testing.T) {
	for _, tc := range []struct {
		name string
		role string
		want enum.ReturnStatus
	}{
		{"owner", "OWNER", enum.ReturnApproved},
		{"admin", "ADMIN", enum.ReturnApproved},
		{"normalized_owner", " owner \t", enum.ReturnApproved},
		{"normalized_admin", " admin ", enum.ReturnApproved},
		{"employee", "EMPLOYEE", enum.ReturnPending},
		{"unknown_role", "CUSTOMER", enum.ReturnPending},
		{"missing_role", "", enum.ReturnPending},
	} {
		t.Run(tc.name, func(t *testing.T) {
			repo := newMockReturnRepo(t)
			forgedActor := uint(999)
			forgedTime := time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)
			input := returnDTO.CreateReturnDTO{
				OriginalOrderID: 12, Reason: "สินค้าผิดรุ่น", RefundMethod: "CASH",
				CreatedBy: forgedActor, Status: "REFUNDED", ApprovedBy: &forgedActor, ApprovedAt: &forgedTime,
				Items: []returnDTO.CreateReturnItemInputDTO{{ProductID: 3, Quantity: 2, UnitPrice: 100}},
			}
			var saved entity.SalesReturn
			before := time.Now()
			repo.createReturnFn = func(ret *entity.SalesReturn, items []entity.SalesReturnItem) error {
				if ret.Status != tc.want || ret.CreatedBy != 42 {
					t.Fatalf("status/creator = %s/%d, want %s/42", ret.Status, ret.CreatedBy, tc.want)
				}
				if tc.want == enum.ReturnApproved {
					if ret.ApprovedBy == nil || *ret.ApprovedBy != 42 || ret.ApprovedAt == nil {
						t.Fatalf("approval must use the authenticated actor: %+v", ret)
					}
					if ret.ApprovedAt.Before(before) || ret.ApprovedAt.After(time.Now()) {
						t.Errorf("approval time must be generated by the server: %v", ret.ApprovedAt)
					}
				} else if ret.ApprovedBy != nil || ret.ApprovedAt != nil {
					t.Errorf("pending return retained forged approval metadata: %+v", ret)
				}
				ret.ID, ret.ReturnNumber = 81, "RTN-2026-00081"
				ret.SalesReturnItems = items
				saved = *ret
				return nil
			}
			repo.getReturnFn = func(id uint) (*entity.SalesReturn, error) {
				if id != 81 || repo.called["CreateReturn"] != 1 {
					t.Fatalf("must fetch the newly created return, id = %d, calls = %v", id, repo.called)
				}
				return &saved, nil
			}
			got, err := returnService.NewReturnService(repo).CreateReturn(input, 42, tc.role)
			if err != nil || got == nil {
				t.Fatalf("CreateReturn() = %+v, %v", got, err)
			}
			if got.ID != 81 || got.ReturnNumber != "RTN-2026-00081" || got.Status != tc.want || got.CreatedBy != 42 {
				t.Errorf("unexpected created response: %+v", got)
			}
		})
	}
}

func TestCreateReturn_ItemsAndRefundAmount(t *testing.T) {
	items := []returnDTO.CreateReturnItemInputDTO{
		{ProductID: 3, Quantity: 2, UnitPrice: 150.25},
		{ProductID: 4, Quantity: 1, UnitPrice: 99.5},
	}
	for _, tc := range []struct {
		name       string
		legacy     bool
		amount     float64
		wantAmount float64
	}{
		{"canonical_items_calculate_total", false, 0, 400},
		{"legacy_items_calculate_total", true, 0, 400},
		{"explicit_partial_refund", false, 120, 120},
	} {
		t.Run(tc.name, func(t *testing.T) {
			repo := newMockReturnRepo(t)
			returnDate := time.Date(2026, 9, 6, 9, 0, 0, 0, time.UTC)
			requestedAt := returnDate.Add(time.Hour)
			input := returnDTO.CreateReturnDTO{
				ReturnNumber: "RTN-2026-00082", OriginalOrderID: 12, Reason: "ผิดรุ่น", Note: "กล่องยังไม่แกะ",
				RefundMethod: "TRANSFER", RefundAmount: tc.amount, ReturnDate: &returnDate, RequestedAt: &requestedAt,
			}
			if tc.legacy {
				input.Items = items
			} else {
				input.SalesReturnItems = items
				// The canonical field wins when both supported input names are present.
				input.Items = []returnDTO.CreateReturnItemInputDTO{{ProductID: 999, Quantity: 1, UnitPrice: 999}}
			}
			var saved entity.SalesReturn
			repo.createReturnFn = func(ret *entity.SalesReturn, gotItems []entity.SalesReturnItem) error {
				wantItems := []entity.SalesReturnItem{
					{ProductID: 3, Quantity: 2, UnitPrice: 150.25, Subtotal: 300.5},
					{ProductID: 4, Quantity: 1, UnitPrice: 99.5, Subtotal: 99.5},
				}
				if !reflect.DeepEqual(gotItems, wantItems) {
					t.Errorf("items = %+v, want %+v", gotItems, wantItems)
				}
				if ret.RefundAmount != tc.wantAmount || ret.OriginalOrderID != 12 || ret.RefundMethod != "TRANSFER" ||
					ret.Reason != input.Reason || ret.Note != input.Note || ret.ReturnNumber != input.ReturnNumber ||
					!ret.ReturnDate.Equal(returnDate) || !ret.RequestedAt.Equal(requestedAt) {
					t.Errorf("incorrect return fields: %+v", ret)
				}
				ret.ID, ret.SalesReturnItems = 82, gotItems
				saved = *ret
				return nil
			}
			repo.getReturnFn = func(id uint) (*entity.SalesReturn, error) { return &saved, nil }
			got, err := returnService.NewReturnService(repo).CreateReturn(input, 42, "EMPLOYEE")
			if err != nil || got == nil {
				t.Fatalf("CreateReturn() = %+v, %v", got, err)
			}
			if got.RefundAmount != tc.wantAmount || len(got.SalesReturnItems) != 2 {
				t.Errorf("incorrect refund response: %+v", got)
			}
		})
	}
}

func TestCreateReturn_RepositoryErrors(t *testing.T) {
	for _, wantErr := range []error{
		returnRepo.ErrOrderInProgress, returnRepo.ErrOrderNotCompleted,
		returnRepo.ErrReturnQuantityExceedsOrder, returnRepo.ErrRefundAmountExceedsOrder,
		errors.New("create failed"),
	} {
		t.Run(wantErr.Error(), func(t *testing.T) {
			repo := newMockReturnRepo(t)
			repo.createReturnFn = func(*entity.SalesReturn, []entity.SalesReturnItem) error { return wantErr }
			got, err := returnService.NewReturnService(repo).CreateReturn(returnDTO.CreateReturnDTO{}, 42, "EMPLOYEE")
			if got != nil || !errors.Is(err, wantErr) {
				t.Errorf("CreateReturn() = %+v, %v, want nil, %v", got, err, wantErr)
			}
		})
	}
}

func TestCreateReturn_FetchFailureReturnsSavedRecord(t *testing.T) {
	repo := newMockReturnRepo(t)
	before := time.Now()
	repo.createReturnFn = func(ret *entity.SalesReturn, items []entity.SalesReturnItem) error {
		ret.ID, ret.ReturnNumber, ret.SalesReturnItems = 83, "RTN-2026-00083", items
		return nil
	}
	repo.getReturnFn = func(id uint) (*entity.SalesReturn, error) {
		if id != 83 {
			t.Fatalf("fetch id = %d, want 83", id)
		}
		return nil, errors.New("read unavailable after commit")
	}
	got, err := returnService.NewReturnService(repo).CreateReturn(returnDTO.CreateReturnDTO{
		OriginalOrderID: 12, Reason: "ผิดรุ่น", RefundMethod: "CASH",
		Items: []returnDTO.CreateReturnItemInputDTO{{ProductID: 3, Quantity: 2, UnitPrice: 50}},
	}, 42, "EMPLOYEE")
	if err != nil || got == nil {
		t.Fatalf("CreateReturn() = %+v, %v", got, err)
	}
	if got.ID != 83 || got.ReturnNumber != "RTN-2026-00083" || got.RefundAmount != 100 || len(got.SalesReturnItems) != 1 {
		t.Errorf("must return the successfully saved record: %+v", got)
	}
	if got.ReturnDate.Before(before) || got.ReturnDate.After(time.Now()) || got.RequestedAt.Before(before) || got.RequestedAt.After(time.Now()) {
		t.Errorf("omitted dates must default to the current time: %+v", got)
	}
}

func TestUpdateReturn_RejectsInvalidTransitions(t *testing.T) {
	for _, tc := range []struct {
		name    string
		from    enum.ReturnStatus
		to      string
		wantErr error
	}{
		{"unknown_status", enum.ReturnPending, "LOST", returnService.ErrInvalidReturnStatus},
		{"blank_status", enum.ReturnPending, " \t", returnService.ErrInvalidReturnStatus},
		{"refund_requires_dedicated_operation", enum.ReturnApproved, " refunded ", returnService.ErrInvalidReturnStatus},
		{"approve_rejected", enum.ReturnRejected, "APPROVED", returnRepo.ErrReturnAlreadyProcessed},
		{"approve_refunded", enum.ReturnRefunded, "APPROVED", returnRepo.ErrReturnAlreadyProcessed},
		{"reject_approved", enum.ReturnApproved, "REJECTED", returnRepo.ErrReturnAlreadyProcessed},
		{"reject_refunded", enum.ReturnRefunded, "REJECTED", returnRepo.ErrReturnAlreadyProcessed},
		{"reject_rejected", enum.ReturnRejected, "REJECTED", returnRepo.ErrReturnAlreadyProcessed},
	} {
		t.Run(tc.name, func(t *testing.T) {
			repo := newMockReturnRepo(t)
			existing := entity.SalesReturn{Model: gorm.Model{ID: 81}, Status: tc.from}
			repo.getReturnFn = func(id uint) (*entity.SalesReturn, error) { return &existing, nil }
			got, err := returnService.NewReturnService(repo).UpdateReturn(81, returnDTO.UpdateReturnDTO{Status: tc.to}, 42)
			if got != nil || !errors.Is(err, tc.wantErr) {
				t.Errorf("UpdateReturn() = %+v, %v, want nil, %v", got, err, tc.wantErr)
			}
			if existing.Status != tc.from || repo.called["GetReturnByID"] != 1 {
				t.Errorf("invalid transition changed existing state or made extra reads: %+v, %v", existing, repo.called)
			}
		})
	}
}

func TestUpdateReturn_ApprovalUsesDedicatedOperation(t *testing.T) {
	for _, alreadyApproved := range []bool{false, true} {
		name := "pending"
		if alreadyApproved {
			name = "already_approved_is_idempotent"
		}
		t.Run(name, func(t *testing.T) {
			repo := newMockReturnRepo(t)
			approvedAt := time.Date(2026, 9, 7, 10, 0, 0, 0, time.UTC)
			wantApprover := uint(42)
			if alreadyApproved {
				wantApprover = 7 // A different user approved the existing record.
			}
			actor := wantApprover
			existing := entity.SalesReturn{Model: gorm.Model{ID: 81}, Status: enum.ReturnPending, Reason: "ผิดรุ่น"}
			approved := existing
			approved.Status, approved.ApprovedBy, approved.ApprovedAt = enum.ReturnApproved, &actor, &approvedAt
			if alreadyApproved {
				existing = approved
			}
			repo.getReturnFn = func(id uint) (*entity.SalesReturn, error) {
				if id != 81 {
					t.Fatalf("id = %d, want 81", id)
				}
				if repo.called["GetReturnByID"] == 1 {
					return &existing, nil
				}
				if !alreadyApproved && repo.called["ApproveReturn"] != 1 {
					t.Fatal("approval must occur before refetch")
				}
				if alreadyApproved {
					return &existing, nil
				}
				return &approved, nil
			}
			if !alreadyApproved {
				repo.approveReturnFn = func(id, approvedBy uint) error {
					if id != 81 || approvedBy != 42 {
						t.Errorf("ApproveReturn(%d, %d), want (81, 42)", id, approvedBy)
					}
					return nil
				}
			}
			forgedActor := uint(999)
			got, err := returnService.NewReturnService(repo).UpdateReturn(81, returnDTO.UpdateReturnDTO{
				Status: " approved ", ApprovedBy: &forgedActor,
			}, 42)
			if err != nil || got == nil {
				t.Fatalf("UpdateReturn() = %+v, %v", got, err)
			}
			if got.Status != enum.ReturnApproved || got.ApprovedBy == nil || *got.ApprovedBy != wantApprover || got.ApprovedAt == nil || !got.ApprovedAt.Equal(approvedAt) {
				t.Errorf("expected persisted approval metadata: %+v", got)
			}
			if alreadyApproved && (existing.ApprovedBy == nil || *existing.ApprovedBy != 7 || existing.ApprovedAt == nil || !existing.ApprovedAt.Equal(approvedAt)) {
				t.Errorf("repeat approval changed the original attribution: %+v", existing)
			}
			if repo.called["GetReturnByID"] != 2 {
				t.Errorf("expected original and persisted reads: %v", repo.called)
			}
		})
	}
}

func TestUpdateReturn_RejectionSetsServerApprovalMetadata(t *testing.T) {
	repo := newMockReturnRepo(t)
	forgedActor := uint(999)
	forgedTime := time.Date(2000, 1, 1, 0, 0, 0, 0, time.UTC)
	existing := entity.SalesReturn{Model: gorm.Model{ID: 81}, Status: enum.ReturnPending, RefundAmount: 100}
	var saved entity.SalesReturn
	repo.getReturnFn = func(id uint) (*entity.SalesReturn, error) {
		if repo.called["GetReturnByID"] == 1 {
			return &existing, nil
		}
		return &saved, nil
	}
	repo.updateReturnFn = func(ret *entity.SalesReturn) error { saved = *ret; return nil }
	before := time.Now()
	got, err := returnService.NewReturnService(repo).UpdateReturn(81, returnDTO.UpdateReturnDTO{
		Status: " rejected ", Reason: "สินค้าใช้งานแล้ว", Note: "แจ้งลูกค้าแล้ว", ApprovedBy: &forgedActor, ApprovedAt: &forgedTime,
	}, 42)
	if err != nil || got == nil {
		t.Fatalf("UpdateReturn() = %+v, %v", got, err)
	}
	if saved.Status != enum.ReturnRejected || saved.ApprovedBy == nil || *saved.ApprovedBy != 42 || saved.ApprovedAt == nil {
		t.Fatalf("rejection metadata must use the server actor: %+v", saved)
	}
	if saved.ApprovedAt.Before(before) || saved.ApprovedAt.After(time.Now()) || saved.Reason != "สินค้าใช้งานแล้ว" || saved.Note != "แจ้งลูกค้าแล้ว" || saved.RefundAmount != 100 {
		t.Errorf("incorrect rejection fields: %+v", saved)
	}
	if existing.Status != enum.ReturnPending || existing.ApprovedAt != nil || existing.ApprovedBy != nil {
		t.Errorf("update mutated the fetched original: %+v", existing)
	}
	if got.Status != enum.ReturnRejected || got.Note != saved.Note {
		t.Errorf("unexpected response: %+v", got)
	}
}

func TestUpdateReturn_EditPreservesApprovalMetadata(t *testing.T) {
	for _, fetchFails := range []bool{false, true} {
		name := "refetched_response"
		if fetchFails {
			name = "saved_response_if_refetch_fails"
		}
		t.Run(name, func(t *testing.T) {
			repo := newMockReturnRepo(t)
			approvedBy, forgedActor := uint(7), uint(999)
			approvedAt := time.Date(2026, 9, 5, 8, 0, 0, 0, time.UTC)
			newDate := approvedAt.AddDate(0, 0, 1)
			existing := entity.SalesReturn{
				Model: gorm.Model{ID: 81}, Status: enum.ReturnApproved, OriginalOrderID: 12,
				ApprovedBy: &approvedBy, ApprovedAt: &approvedAt, RefundAmount: 100,
			}
			var saved entity.SalesReturn
			repo.getReturnFn = func(id uint) (*entity.SalesReturn, error) {
				if repo.called["GetReturnByID"] == 1 {
					return &existing, nil
				}
				if fetchFails {
					return nil, errors.New("read unavailable after commit")
				}
				persisted := saved
				persisted.ReturnNumber = "RTN-2026-00081"
				return &persisted, nil
			}
			repo.updateReturnFn = func(ret *entity.SalesReturn) error { saved = *ret; return nil }
			got, err := returnService.NewReturnService(repo).UpdateReturn(81, returnDTO.UpdateReturnDTO{
				ReturnDate: &newDate, Reason: "ผิดรุ่น", Note: "แก้ไขหมายเหตุ", RefundAmount: 80, RefundMethod: "TRANSFER",
				ApprovedBy: &forgedActor, ApprovedAt: &newDate,
			}, 42)
			if err != nil || got == nil {
				t.Fatalf("UpdateReturn() = %+v, %v", got, err)
			}
			if saved.ID != 81 || saved.OriginalOrderID != 12 || saved.Status != enum.ReturnApproved ||
				saved.ApprovedBy == nil || *saved.ApprovedBy != 7 || saved.ApprovedAt == nil || !saved.ApprovedAt.Equal(approvedAt) {
				t.Errorf("existing approval metadata must be preserved: %+v", saved)
			}
			if !saved.ReturnDate.Equal(newDate) || saved.Reason != "ผิดรุ่น" || saved.Note != "แก้ไขหมายเหตุ" || saved.RefundAmount != 80 || saved.RefundMethod != "TRANSFER" {
				t.Errorf("editable fields were not saved: %+v", saved)
			}
			if got.ID != 81 || got.RefundAmount != 80 || got.Note != saved.Note {
				t.Errorf("unexpected response: %+v", got)
			}
			if !fetchFails && got.ReturnNumber != "RTN-2026-00081" {
				t.Errorf("must use persisted response: %+v", got)
			}
		})
	}
}

func TestUpdateReturn_RepositoryErrors(t *testing.T) {
	for _, stage := range []string{"initial_read", "approve", "approval_refetch", "update"} {
		t.Run(stage, func(t *testing.T) {
			repo := newMockReturnRepo(t)
			wantErr := errors.New(stage + " failed")
			existing := entity.SalesReturn{Model: gorm.Model{ID: 81}, Status: enum.ReturnPending}
			repo.getReturnFn = func(id uint) (*entity.SalesReturn, error) {
				if stage == "initial_read" || repo.called["GetReturnByID"] > 1 {
					return nil, wantErr
				}
				return &existing, nil
			}
			input := returnDTO.UpdateReturnDTO{Note: "แก้ไขหมายเหตุ"}
			if stage == "approve" || stage == "approval_refetch" {
				input.Status = "APPROVED"
				repo.approveReturnFn = func(uint, uint) error {
					if stage == "approve" {
						return wantErr
					}
					return nil
				}
			}
			if stage == "update" {
				repo.updateReturnFn = func(*entity.SalesReturn) error { return wantErr }
			}
			got, err := returnService.NewReturnService(repo).UpdateReturn(81, input, 42)
			if got != nil || !errors.Is(err, wantErr) {
				t.Errorf("UpdateReturn() = %+v, %v, want nil, %v", got, err, wantErr)
			}
			wantReads := 1
			if stage == "approval_refetch" {
				wantReads = 2
			}
			if repo.called["GetReturnByID"] != wantReads {
				t.Errorf("must stop after failure: %v", repo.called)
			}
		})
	}
}

func TestProcessRefund_ReturnsPersistedRefund(t *testing.T) {
	repo := newMockReturnRepo(t)
	actor := uint(42)
	refundedAt := time.Date(2026, 9, 7, 11, 0, 0, 0, time.UTC)
	repo.processRefundFn = func(id, processedBy uint) error {
		if id != 81 || processedBy != actor {
			t.Errorf("ProcessRefund(%d, %d), want (81, 42)", id, processedBy)
		}
		return nil
	}
	repo.getReturnFn = func(id uint) (*entity.SalesReturn, error) {
		if id != 81 || repo.called["ProcessRefund"] != 1 {
			t.Fatalf("must process refund before fetching: id=%d, calls=%v", id, repo.called)
		}
		return &entity.SalesReturn{
			Model: gorm.Model{ID: 81}, Status: enum.ReturnRefunded, RefundAmount: 400,
			RefundMethod: "CASH", RefundedBy: &actor, RefundedAt: &refundedAt,
		}, nil
	}
	got, err := returnService.NewReturnService(repo).ProcessRefund(81, actor)
	if err != nil || got == nil {
		t.Fatalf("ProcessRefund() = %+v, %v", got, err)
	}
	if got.ID != 81 || got.Status != enum.ReturnRefunded || got.RefundAmount != 400 || got.RefundMethod != "CASH" ||
		got.RefundedBy == nil || *got.RefundedBy != actor || got.RefundedAt == nil || !got.RefundedAt.Equal(refundedAt) {
		t.Errorf("incorrect persisted refund response: %+v", got)
	}
}

func TestProcessRefund_RepositoryErrors(t *testing.T) {
	for _, wantErr := range []error{
		returnRepo.ErrReturnNotApproved, returnRepo.ErrReturnAlreadyProcessed,
		returnRepo.ErrInvalidRefundMethod, returnRepo.ErrRefundRequiresCustomer,
		returnRepo.ErrRefundAmountExceedsOrder, gorm.ErrRecordNotFound,
	} {
		t.Run(wantErr.Error(), func(t *testing.T) {
			repo := newMockReturnRepo(t)
			repo.processRefundFn = func(uint, uint) error { return wantErr }
			got, err := returnService.NewReturnService(repo).ProcessRefund(81, 42)
			if got != nil || !errors.Is(err, wantErr) {
				t.Errorf("ProcessRefund() = %+v, %v, want nil, %v", got, err, wantErr)
			}
		})
	}
}

func TestProcessRefund_FetchError(t *testing.T) {
	repo := newMockReturnRepo(t)
	wantErr := errors.New("refund read failed")
	repo.processRefundFn = func(uint, uint) error { return nil }
	repo.getReturnFn = func(uint) (*entity.SalesReturn, error) { return nil, wantErr }
	got, err := returnService.NewReturnService(repo).ProcessRefund(81, 42)
	if got != nil || !errors.Is(err, wantErr) {
		t.Errorf("ProcessRefund() = %+v, %v, want nil, %v", got, err, wantErr)
	}
}

func TestDeleteReturn(t *testing.T) {
	for _, tc := range []struct {
		name string
		err  error
	}{
		{"success", nil}, {"repository_failure", errors.New("delete failed")},
	} {
		t.Run(tc.name, func(t *testing.T) {
			repo := newMockReturnRepo(t)
			repo.deleteReturnFn = func(id uint) error {
				if id != 81 {
					t.Errorf("DeleteReturn id = %d, want 81", id)
				}
				return tc.err
			}
			if err := returnService.NewReturnService(repo).DeleteReturn(81); !errors.Is(err, tc.err) {
				t.Errorf("DeleteReturn() = %v, want %v", err, tc.err)
			}
			if repo.called["DeleteReturn"] != 1 {
				t.Errorf("expected exactly one delete: %v", repo.called)
			}
		})
	}
}
